source 'http://ruby.taobao.org'

gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
end

# 更友好的出错页面
group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'database_cleaner', '~> 1.4.1'
  gem "factory_girl_rails"
  gem 'capybara'
end

gem 'mongoid', '~> 4.0.2'
gem 'haml'

# -------------

gem 'lily-components', path: '../'

gem 'bootstrap-sass', '~> 3.3.5'
gem 'react-rails', '~> 1.2.0'
gem 'sprockets-coffee-react', '~> 3.0.1'